<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net481</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>7.3</LangVersion>
    <RootNamespace>KjTabBar</RootNamespace>

    <AssemblyName>KjTabBar</AssemblyName>
    <ApplicationManifest>Properties\app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\Icons\app_icon.ico</ApplicationIcon>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <Deterministic>true</Deterministic>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\Icons\app_icon.png" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Configuration.Install" />
    <Reference Include="System.Management" />
    <Reference Include="System.Security" />
  </ItemGroup>
</Project>
